import { promises as fs } from 'fs';
import path from 'path';

export type RouteEntry = {
  route: string;
  file: string;
};

export type GroupedFiles = {
  group: string;
  files: string[];
};

export type ArchitectureIndex = {
  schemaVersion: number;
  appRoot: string;
  generatedBy: string;
  commands: {
    dev: string;
    unitTests: string;
    e2eTests: string;
    refreshArchitecture: string;
  };
  keyConfigFiles: string[];
  appShellFiles: string[];
  appRoutes: RouteEntry[];
  specialRoutes: RouteEntry[];
  apiRoutes: RouteEntry[];
  sharedComponents: string[];
  libraryGroups: GroupedFiles[];
  unitTests: string[];
  e2eSpecs: string[];
  e2eFlowDoc: string;
  adrFiles: string[];
};

const APP_ROUTE_SUFFIX = `${path.sep}page.tsx`;
const API_ROUTE_SUFFIX = `${path.sep}route.ts`;

function toPosix(filePath: string): string {
  return filePath.split(path.sep).join('/');
}

function toRepoRelative(repoRoot: string, filePath: string): string {
  return toPosix(path.relative(repoRoot, filePath));
}

async function walkFiles(rootDir: string): Promise<string[]> {
  const entries = await fs.readdir(rootDir, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const fullPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      return walkFiles(fullPath);
    }
    return [fullPath];
  }));

  return files.flat();
}

function stripRouteGroups(routePath: string): string {
  return routePath
    .split('/')
    .filter((segment) => segment !== '' && !segment.startsWith('(') && !segment.startsWith('@'))
    .join('/');
}

export function appPageFileToRoute(file: string): string {
  const normalized = toPosix(file);
  const relative = normalized.replace(/^apps\/web\/app\/?/, '').replace(/\/?page\.tsx$/, '');
  const routePath = stripRouteGroups(relative);
  return routePath === '' ? '/' : `/${routePath}`;
}

export function appSpecialFileToRoute(file: string): string | null {
  const normalized = toPosix(file);
  const relative = normalized.replace(/^apps\/web\/app\/?/, '');

  if (relative === 'manifest.ts') {
    return '/manifest.webmanifest';
  }

  if (relative === 'favicon.ico') {
    return '/favicon.ico';
  }

  return null;
}

export function apiRouteFileToRoute(file: string): string {
  const normalized = toPosix(file);
  const relative = normalized.replace(/^apps\/web\/app\/api\//, '').replace(/\/route\.ts$/, '');
  return `/api/${relative}`;
}

function groupLibraryFiles(files: string[]): GroupedFiles[] {
  const groups = new Map<string, string[]>();

  files.forEach((file) => {
    const relative = toPosix(file).replace(/^apps\/web\/lib\//, '');
    const firstSlash = relative.indexOf('/');
    const group = firstSlash === -1 ? 'root' : relative.slice(0, firstSlash);
    const groupFiles = groups.get(group) ?? [];
    groupFiles.push(toPosix(file));
    groups.set(group, groupFiles);
  });

  return Array.from(groups.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([group, groupFiles]) => ({
      group,
      files: groupFiles.sort(),
    }));
}

function renderRouteTable(entries: RouteEntry[]): string[] {
  if (entries.length === 0) {
    return ['_None_'];
  }

  return [
    '| Route | File |',
    '| --- | --- |',
    ...entries.map((entry) => `| \`${entry.route}\` | \`${entry.file}\` |`),
  ];
}

function renderFileList(files: string[]): string[] {
  if (files.length === 0) {
    return ['_None_'];
  }

  return files.map((file) => `- \`${file}\``);
}

function renderGroupedFiles(groups: GroupedFiles[]): string[] {
  if (groups.length === 0) {
    return ['_None_'];
  }

  return groups.flatMap((group) => [
    `### ${group.group}`,
    ...renderFileList(group.files),
    '',
  ]).slice(0, -1);
}

export function renderArchitectureMarkdown(index: ArchitectureIndex): string {
  const lines = [
    '# Architecture Index',
    '',
    '> Generated from the filesystem by `bun run docs:architecture`. Do not edit this file by hand.',
    '',
    '## Scope',
    `- Product surface: \`${index.appRoot}\``,
    `- Refresh command: \`${index.commands.refreshArchitecture}\``,
    `- Unit tests: \`${index.commands.unitTests}\``,
    `- E2E tests: \`${index.commands.e2eTests}\``,
    '',
    '## Counts',
    `- App routes: ${index.appRoutes.length}`,
    `- Special routes: ${index.specialRoutes.length}`,
    `- API routes: ${index.apiRoutes.length}`,
    `- Shared components: ${index.sharedComponents.length}`,
    `- Library modules: ${index.libraryGroups.reduce((sum, group) => sum + group.files.length, 0)}`,
    `- Unit tests: ${index.unitTests.length}`,
    `- E2E specs: ${index.e2eSpecs.length}`,
    '',
    '## Key Config Files',
    ...renderFileList(index.keyConfigFiles),
    '',
    '## App Shell Files',
    ...renderFileList(index.appShellFiles),
    '',
    '## App Routes',
    ...renderRouteTable(index.appRoutes),
    '',
    '## Special Routes',
    ...renderRouteTable(index.specialRoutes),
    '',
    '## API Routes',
    ...renderRouteTable(index.apiRoutes),
    '',
    '## Shared Components',
    ...renderFileList(index.sharedComponents),
    '',
    '## Library Modules',
    ...renderGroupedFiles(index.libraryGroups),
    '',
    '## Unit Tests',
    ...renderFileList(index.unitTests),
    '',
    '## E2E Specs',
    ...renderFileList(index.e2eSpecs),
    '',
    '## Flow Coverage Doc',
    `- \`${index.e2eFlowDoc}\``,
    '',
    '## ADRs',
    ...renderFileList(index.adrFiles),
    '',
  ];

  return `${lines.join('\n')}\n`;
}

export async function buildArchitectureIndex(repoRoot: string): Promise<ArchitectureIndex> {
  const appRoot = path.join(repoRoot, 'apps/web');
  const appDir = path.join(appRoot, 'app');
  const libDir = path.join(appRoot, 'lib');
  const componentsDir = path.join(appDir, 'components');
  const testsDir = path.join(appRoot, '__tests__');
  const e2eDir = path.join(appRoot, 'e2e');
  const adrDir = path.join(repoRoot, 'docs/adr');

  const [
    appFiles,
    libFiles,
    componentFiles,
    unitTestFiles,
    e2eFiles,
    adrFiles,
  ] = await Promise.all([
    walkFiles(appDir),
    walkFiles(libDir),
    walkFiles(componentsDir),
    walkFiles(testsDir),
    walkFiles(e2eDir),
    fs.access(adrDir).then(() => walkFiles(adrDir)).catch(() => []),
  ]);

  const normalizedLibFiles = libFiles.map((file) => toRepoRelative(repoRoot, file)).sort();
  const normalizedComponentFiles = componentFiles.map((file) => toRepoRelative(repoRoot, file)).sort();
  const normalizedUnitTestFiles = unitTestFiles.map((file) => toRepoRelative(repoRoot, file)).sort();
  const normalizedE2eFiles = e2eFiles.map((file) => toRepoRelative(repoRoot, file)).sort();
  const normalizedAdrFiles = adrFiles
    .map((file) => toRepoRelative(repoRoot, file))
    .filter((file) => file.endsWith('.md') && !file.endsWith('README.md'))
    .sort();
  const normalizedRelativeAppFiles = appFiles.map((file) => toRepoRelative(repoRoot, file)).sort();

  const appRoutes = normalizedRelativeAppFiles
    .filter((file) => file.endsWith('/page.tsx'))
    .map((file) => ({
      route: appPageFileToRoute(file),
      file,
    }));

  const specialRoutes = normalizedRelativeAppFiles
    .map((file) => ({
      route: appSpecialFileToRoute(file),
      file,
    }))
    .filter((entry): entry is RouteEntry => entry.route !== null);

  const apiRoutes = normalizedRelativeAppFiles
    .filter((file) => file.includes('/app/api/') && file.endsWith('/route.ts'))
    .map((file) => ({
      route: apiRouteFileToRoute(file),
      file,
    }));

  return {
    schemaVersion: 1,
    appRoot: 'apps/web',
    generatedBy: 'apps/web/scripts/generate-architecture-index.ts',
    commands: {
      dev: 'bun run dev',
      unitTests: 'bun run test:run',
      e2eTests: 'bun run test:e2e',
      refreshArchitecture: 'bun run docs:architecture',
    },
    keyConfigFiles: [
      'package.json',
      'apps/web/package.json',
      'apps/web/tsconfig.json',
      'apps/web/next.config.ts',
      'apps/web/vitest.config.ts',
      'apps/web/playwright.config.ts',
      'apps/web/eslint.config.mjs',
    ],
    appShellFiles: [
      'apps/web/app/layout.tsx',
      'apps/web/app/providers.tsx',
      'apps/web/app/globals.css',
    ],
    appRoutes,
    specialRoutes,
    apiRoutes,
    sharedComponents: normalizedComponentFiles,
    libraryGroups: groupLibraryFiles(normalizedLibFiles),
    unitTests: normalizedUnitTestFiles.filter((file) => file.endsWith('.test.ts') || file.endsWith('.test.tsx')),
    e2eSpecs: normalizedE2eFiles.filter((file) => file.endsWith('.spec.ts')),
    e2eFlowDoc: 'apps/web/e2e/flows.md',
    adrFiles: normalizedAdrFiles,
  };
}
